apiVersion: v1
kind: Pod
metadata:
  name: dummy-pod
spec:
  containers:
    - name: demo-container
      image: busybox
      command: ["sleep", "3600"]
      resources:
        limits:
          nvidia.com/gpu: 2
          example.com/nic: 1
