---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dummy-device-plugin
  namespace: kube-system
  labels:
    app: dummy-device-plugin
spec:
  selector:
    matchLabels:
      app: dummy-device-plugin
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        app: dummy-device-plugin
    spec:
      # Optional: restrict to labeled nodes only.
      # nodeSelector:
      #   dummy-device-plugin: 'true'
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
      hostNetwork: true
      containers:
        - image: ghcr.io/nosportugal/k8s-dummy-device-plugin:latest
          name: dummy-device-plugin
          volumeMounts:
            - name: device-plugin
              mountPath: /var/lib/kubelet/device-plugins
            - name: config
              mountPath: /dummyResources.json
              subPath: dummyResources.json
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: config
          configMap:
            name: dummy-device-plugin-config
            items:
              - key: dummyResources.json
                path: dummyResources.json
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dummy-device-plugin-config
  namespace: kube-system
data:
  dummyResources.json: |
    [
      {
        "resourceName": "nvidia.com/gpu",
        "count": 4
      },
      {
        "resourceName": "example.com/nic",
        "count": 2
      }
    ]
